<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/functions.php'; require_once __DIR__ . '/../../auth/guard.php'; require_once __DIR__ . '/../../config/database.php'; require_once __DIR__ . '/../../includes/module2_helpers.php'; requireAdmin();
$title='Thêm căn hộ'; $types=$pdo->query('SELECT MaLoai,TenLoai,GiaThueChuan FROM LoaiCanHo ORDER BY TenLoai')->fetchAll(); $errors=[]; $data=['SoPhong'=>'','MaLoai'=>'','DienTich'=>'','GiaThue'=>'','TrangThai'=>'Trống','MoTa'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){ module2_require_csrf(); foreach(['SoPhong','DienTich','GiaThue','MoTa'] as $key) $data[$key]=trim((string)($_POST[$key]??'')); $data['MaLoai']=(int)($_POST['MaLoai']??0); $data['TrangThai']=(string)($_POST['TrangThai']??'');
if($data['SoPhong']===''||mb_strlen($data['SoPhong'])>20)$errors['SoPhong']='Số phòng bắt buộc, tối đa 20 ký tự.'; if($data['MaLoai']<=0)$errors['MaLoai']='Vui lòng chọn loại căn.'; if($data['DienTich']===''||!is_numeric($data['DienTich'])||(float)$data['DienTich']<=0)$errors['DienTich']='Diện tích phải > 0.'; if($data['GiaThue']===''||!is_numeric($data['GiaThue'])||(float)$data['GiaThue']<0)$errors['GiaThue']='Giá thuê phải >= 0.'; if(!in_array($data['TrangThai'],['Trống','Đang thuê','Bảo trì'],true))$errors['TrangThai']='Trạng thái không hợp lệ.'; if(mb_strlen($data['MoTa'])>255)$errors['MoTa']='Mô tả tối đa 255 ký tự.';
$hasFiles=isset($_FILES['images']['name'])&&is_array($_FILES['images']['name'])&&count(array_filter($_FILES['images']['name']))>0; if(!$hasFiles)$errors['images']='Căn hộ phải có ít nhất 1 ảnh đại diện.'; $s=$pdo->prepare('SELECT COUNT(*) FROM CanHo WHERE SoPhong=:sp');$s->execute([':sp'=>$data['SoPhong']]);if((int)$s->fetchColumn()>0)$errors['SoPhong']='Số phòng đã tồn tại.';
if(!$errors){try{$pdo->beginTransaction();$s=$pdo->prepare('INSERT INTO CanHo(SoPhong,MaLoai,DienTich,GiaThue,TrangThai,MoTa) VALUES(:sp,:loai,:dt,:gia,:tt,:mota)');$s->execute([':sp'=>$data['SoPhong'],':loai'=>$data['MaLoai'],':dt'=>(float)$data['DienTich'],':gia'=>(float)$data['GiaThue'],':tt'=>$data['TrangThai'],':mota'=>$data['MoTa']?:null]);$id=(int)$pdo->lastInsertId();module2_upload_images($_FILES['images'],$id,$pdo,dirname(__DIR__,2).'/uploads/can-ho','uploads/can-ho');module2_repair_cover($pdo,$id);$pdo->commit();setFlash('success','Thêm căn hộ thành công.');redirect('/admin/can-ho/detail.php?id='.$id);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log($e->getMessage());$errors['general']='Không thể thêm căn hộ. Kiểm tra lại dữ liệu và ảnh.';}}}
require_once __DIR__ . '/../../includes/header.php';
?><div class="page-header"><div><h1>Thêm căn hộ</h1><p class="text-muted">Nhập thông tin căn và upload nhiều ảnh.</p></div><a class="btn btn-light" href="index.php">Quay lại</a></div><?php if(isset($errors['general'])):?><div class="alert alert-danger"><?=e($errors['general'])?></div><?php endif;?><form method="post" enctype="multipart/form-data" class="form-card"><input type="hidden" name="csrf_token" value="<?=e(module2_csrf_token())?>"><div class="form-grid"><div class="form-group"><label>Số phòng *</label><input name="SoPhong" maxlength="20" value="<?=e($data['SoPhong'])?>" required><?php if(isset($errors['SoPhong'])):?><small class="error-text"><?=e($errors['SoPhong'])?></small><?php endif;?></div><div class="form-group"><label>Loại căn *</label><select name="MaLoai" required><option value="">-- Chọn --</option><?php foreach($types as $t):?><option value="<?=$t['MaLoai']?>" <?=$data['MaLoai']==(int)$t['MaLoai']?'selected':''?>><?=e($t['TenLoai'])?> — <?=formatMoney($t['GiaThueChuan'])?></option><?php endforeach;?></select><?php if(isset($errors['MaLoai'])):?><small class="error-text"><?=e($errors['MaLoai'])?></small><?php endif;?></div><div class="form-group"><label>Diện tích (m²) *</label><input type="number" name="DienTich" min="0.01" step="0.01" value="<?=e($data['DienTich'])?>" required></div><div class="form-group"><label>Giá thuê *</label><input type="number" name="GiaThue" min="0" step="0.01" value="<?=e($data['GiaThue'])?>" required></div><div class="form-group"><label>Trạng thái *</label><select name="TrangThai"><?php foreach(['Trống','Đang thuê','Bảo trì'] as $s):?><option <?=$data['TrangThai']===$s?'selected':''?>><?=e($s)?></option><?php endforeach;?></select></div></div><div class="form-group"><label>Mô tả</label><textarea name="MoTa" maxlength="255" rows="4"><?=e($data['MoTa'])?></textarea></div><div class="form-group"><label>Ảnh căn hộ *</label><input type="file" name="images[]" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" multiple required><?php if(isset($errors['images'])):?><small class="error-text"><?=e($errors['images'])?></small><?php endif;?></div><div class="form-actions"><button class="btn btn-primary">Lưu căn hộ</button><a class="btn btn-light" href="index.php">Hủy</a></div></form><?php require_once __DIR__ . '/../../includes/footer.php'; ?>